# -*- coding: utf-8 -*-
"""Copy of DAApratical 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ArCY2wVXxn9eF_cU424O4fMYAhWaTKhk
"""

import time

def matrix_chain_order(p):
    n = len(p) - 1   # number of matrices
    m = [[0 for _ in range(n)] for _ in range(n)]

    # L is chain length
    for L in range(2, n + 1):
        for i in range(n - L + 1):
            j = i + L - 1
            m[i][j] = float('inf')

            for k in range(i, j):
                q = (m[i][k] +
                     m[k + 1][j] +
                     p[i] * p[k + 1] * p[j + 1])

                if q < m[i][j]:
                    m[i][j] = q

    return m[0][n - 1]


# 🔹 User Input
n = int(input("Enter number of matrices: "))
p = []

print("Enter dimensions array (size n+1):")
for i in range(n + 1):
    val = int(input(f"p[{i}] = "))
    p.append(val)

# 🔹 Time Measurement
start_time = time.time()

result = matrix_chain_order(p)

end_time = time.time()

# 🔹 Output
print("\nMinimum number of multiplications:", result)
print("Execution Time:", end_time - start_time, "seconds")

# 🔹 Time Complexity
print("Time Complexity: O(n^3)")