# -*- coding: utf-8 -*-
"""pratical-4 daa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cADu7FOPEOXI30o1SiJUCcNH2oYW5YFJ
"""

# Factorial using Iterative and Recursive Methods
# Includes Input, Output, and Time Analysis

import time

# Iterative factorial function
def factorial_iterative(n):
    fact = 1
    for i in range(1, n + 1):
        fact *= i
    return fact

# Recursive factorial function
def factorial_recursive(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial_recursive(n - 1)

# Input
n = int(input("Enter a number: "))

# Iterative Method Execution
start_iter = time.time()
iter_result = factorial_iterative(n)
end_iter = time.time()

# Recursive Method Execution
start_rec = time.time()
rec_result = factorial_recursive(n)
end_rec = time.time()

# Output
print("\nIterative Factorial:", iter_result)
print("Recursive Factorial:", rec_result)

# Time Analysis
print("\nTime Taken (Iterative):", end_iter - start_iter, "seconds")
print("Time Taken (Recursive):", end_rec - start_rec, "seconds")

# Time Complexity (Displayed in Output)
print("\nTime Complexity:")
print("Iterative Method: O(n)")
print("Recursive Method: O(n)")