# -*- coding: utf-8 -*-
"""pratical-10(DAA)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CgI8Tgjk55hOV0r3ZYpYbduaMuTdSf1x
"""

# Implementation of Kruskal's Algorithm

# Function to find the parent of a vertex
def find(parent, vertex):
    if parent[vertex] != vertex:
        parent[vertex] = find(parent, parent[vertex])
    return parent[vertex]


# Function to join two sets
def union(parent, rank, u, v):
    root_u = find(parent, u)
    root_v = find(parent, v)

    if root_u != root_v:
        if rank[root_u] < rank[root_v]:
            parent[root_u] = root_v
        elif rank[root_u] > rank[root_v]:
            parent[root_v] = root_u
        else:
            parent[root_v] = root_u
            rank[root_u] += 1


# Kruskal's Algorithm
def kruskal(vertices, edges):
    # Sort edges according to their weight
    edges.sort(key=lambda x: x[2])

    parent = {v: v for v in vertices}
    rank = {v: 0 for v in vertices}

    mst = []
    total_cost = 0

    print("Edges selected for Minimum Spanning Tree:")

    for u, v, weight in edges:
        root_u = find(parent, u)
        root_v = find(parent, v)

        # Add edge only if it does not form a cycle
        if root_u != root_v:
            mst.append((u, v, weight))
            total_cost += weight
            union(parent, rank, u, v)

            print(f"{u} -- {v} : {weight}")

    print("\nMinimum Spanning Tree (MST):")
    for u, v, weight in mst:
        print(f"{u} -- {v} : {weight}")

    print("\nTotal cost of MST:", total_cost)


# Vertices
vertices = ['A', 'B', 'C', 'D', 'E']

# Edges: (vertex1, vertex2, weight)
edges = [
    ('A', 'B', 2),
    ('A', 'C', 3),
    ('B', 'C', 1),
    ('B', 'D', 4),
    ('C', 'D', 5),
    ('C', 'E', 6),
    ('D', 'E', 7)
]

# Run Kruskal's Algorithm
kruskal(vertices, edges)