# -*- coding: utf-8 -*-
"""PRATICAL 3 DAA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z5f5q22oM309xxrjW1ki8M4NvDEFHf1r
"""

import time

# Heapify function
def heapify(arr, n, i):
    largest = i
    left = 2 * i + 1
    right = 2 * i + 2

    if left < n and arr[left] > arr[largest]:
        largest = left

    if right < n and arr[right] > arr[largest]:
        largest = right

    if largest != i:
        arr[i], arr[largest] = arr[largest], arr[i]
        heapify(arr, n, largest)


# Heap Sort function
def heap_sort(arr):
    n = len(arr)

    # Build max heap
    for i in range(n // 2 - 1, -1, -1):
        heapify(arr, n, i)

    # Extract elements
    for i in range(n - 1, 0, -1):
        arr[i], arr[0] = arr[0], arr[i]
        heapify(arr, i, 0)


# ---- User Input ----
arr = list(map(int, input("Enter elements separated by space: ").split()))

print("User Input Array:", arr)

# ---- Execution Time Start ----
start_time = time.time()

heap_sort(arr)

# ---- Execution Time End ----
end_time = time.time()

# ---- Output ----
print("Sorted Array:", arr)

# Time Complexity
print("\nTime Complexity of Heap Sort:")
print("Best Case   : O(n log n)")
print("Average Case: O(n log n)")
print("Worst Case  : O(n log n)")

# Execution Time
print("\nExecution Time: {:.6f} seconds".format(end_time - start_time))