# -*- coding: utf-8 -*-
"""PRTICAL-7 DAA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QSYoI3yn8biOeKOiO_np-WOAxthq-4hH
"""

# Coin Change Problem using Dynamic Programming
# Find minimum number of coins required to make a given amount

def coin_change(coins, amount):
    dp = [float('inf')] * (amount + 1)
    dp[0] = 0  # Base case

    for i in range(1, amount + 1):
        for coin in coins:
            if coin <= i:
                dp[i] = min(dp[i], dp[i - coin] + 1)

    return dp[amount] if dp[amount] != float('inf') else -1

# Input
coins = list(map(int, input("Enter coin denominations (space-separated): ").split()))
amount = int(input("Enter the amount: "))

# Execution
result = coin_change(coins, amount)

# Output
if result != -1:
    print("\nMinimum coins required:", result)
else:
    print("\nChange cannot be made with given coins")

# Time Complexity Output
print("\nTime Complexity: O(n * amount)")